Extended and reworked models, dockerfile cleanup
CombiRWTH/medical-staff-assessment pull request #55
Opened 2024-11-19 13:49 UTC by jensUhl

closes #42 .

Added the missing data models. Reworked alot of the data models and adapted `handleQuestions.py`. Cleaned up `Dockerfile` (only cosmetics).

**Added following data models:**

- PatientTransfers (was PatientJourney before)
- StationOccupancy
- StationWorkloadDaily (was CaregiversStation before)
- StationWorkloadMonthly (stores monthly averages of 

**Changes made to data models:**

- `Patient`: added current station, added dates for admission, discharged and deceased
- `PatientJourney`: renamed to PatientTransfers (in medical context, patient journey usually describes the analysis and development of a patients illness, not his location)
- `CaregiversStation`: renamed to StationWorkloadDaily. Station Workload has to be tracked daily, the monthly averages are calculated based on the daily entries and stored in extra table (StationWorkloadMonthly)

Added detailed comments for data fields in `models.py` and how they are calculated.
Reworked table descriptions.

`StationOccupancy` will be filled with data calculated from `Patient` and

2024-11-20 07:16 UTC, lennart-huesing requested changes
Throws many errors on startup since naming is wrong:
medical-staff-assessment-web-1  | ERRORS:
medical-staff-assessment-web-1  | backend.DailyClassification: (models.E012) 'unique_together' refers to the nonexistent field 'classification_date'.
medical-staff-assessment-web-1  | SystemCheckError: System check identified some issues:

2024-11-20 07:20 UTC, lennart-huesing requested changes
https://www.flake8rules.com/rules/E261.html
Two spaces should be before the inline comment

2024-11-20 07:20 UTC, lennart-huesing commented on backend/models.py
> +    severity = models.IntegerField()            # Degree of needed help, increasing from 1 to 4
Indent

2024-11-20 07:20 UTC, lennart-huesing commented on backend/models.py
> +    name = models.CharField(max_length=128)     # Field name, e.g. 'Allgemeine Pflege'
Indent

2024-11-21 14:27 UTC, benCoder01 approved these changes
Looks good to me

2024-11-21 15:56 UTC, lennart-huesing approved these changes

2024-11-22 17:03 UTC, merged