Extend returned information for the requested classification
CombiRWTH/medical-staff-assessment pull request #72
Opened 2024-11-25 18:17 UTC by lennart-huesing

I added the calculated a,s index to the DailyClassification model and return them when submitting the questions.

2024-11-27 13:06 UTC, benCoder01 reviewed
Wouldnt it make more sense to return the same json struct as in the request body? The frontend teams wanted to to make the post request every time a box is ticked. If we would return the selected care services they could update their state on every post request.

2024-11-28 11:23 UTC, benCoder01 requested changes
I think the there are some fields missing, which are required by the frontend team:
```json
{
   "id":"int",
   "isDayOfAdmission":"bool",
   "isDayOfDischarge":"bool",
   "isInIsolation":"bool"
   "fields":[
      {
         "id":"int",
         "name":"string",
         "short":"string",
         "categories":[
            {
               "id":"int",
               "name":"string",
               "short":"string", // Empty string possible for now
               "severities":[
                  {
                     "severity":"int",
                     "options":[
                        {
                           "id":"int",
                           "index":"int",
                           "short":"string", // Empty string possible for now
                           "description":"string"
                        }
                     ]
                  }
               ]
            }
         ]
      }
   ]
}
```
everything in the fields array seems to conform with the above requirements, but the top level fields are simetimes missing.

2024-11-29 09:04 UTC, lennart-huesing commented
I now added placeholders. I think this might be party of https://github.com/CombiRWTH/medical-staff-assessment/issues/44 to collect these information. If not it is a seperate issue.

2024-11-30 14:31 UTC, benCoder01 approved these changes

2024-11-30 14:32 UTC, merged